module.exports = {
  User: require('./User'),
  Customer: require('./Customer'),
  Driver: require('./Driver'),
  Vehicle: require('./Vehicle'),
  Order: require('./Order'),
  OrderStatusHistory: require('./OrderStatusHistory'),
  Message: require('./Message'),
  Rating: require('./Rating'),
  Complaint: require('./Complaint'),
  OrderIssue: require('./OrderIssue'),
  WalletTransaction: require('./WalletTransaction'),
  PromoCode: require('./PromoCode'),
  PromoUsage: require('./PromoUsage'),
  PricingRule: require('./PricingRule'),
  SystemSetting: require('./SystemSetting'),
  RefreshToken: require('./RefreshToken'),
  OtpCode: require('./OtpCode'),
  Notification: require('./Notification'),
  AuditLog: require('./AuditLog'),
};
